### PR TITLE
Fix: Duplicate and null prefix for sort

### LINKED ISSUE #196: Bug: Calling varargs method with null triggers ambiguous warning in ModelManagerTest
Image

### LINKED ISSUE #208: Bug: Fix duplicate prefix for sort

### PR DESCRIPTION
**Pull request by carineang**
Closes #196 
Closes #208

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 1]
```diff
@@ -34,37 +37,90 @@ public SortCommand parse(String args) throws ParseException {
...
+
+    /**
+     * Validates if a given prefix is a recognized sorting prefix.
+     *
+     * @param prefix The prefix string to validate.
+     * @return True if the prefix is valid, false otherwise.
+     */
+    private boolean isValidPrefix(String prefix) {
+        return prefix.equals("n/") || prefix.equals("p/") || prefix.equals("e/") || prefix.equals("a/")
+                || prefix.equals("t/");
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java:57]: If you want 
Maybe have an array or dictionary or set called
VALID_PREFIXES
Or something
But honestly very minor

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 2]
```diff
@@ -34,37 +37,90 @@ public SortCommand parse(String args) throws ParseException {
...
+     * Checks whether the provided prefixes contain any duplicates.
+     * If duplicates are found, a ParseException is thrown.
+     *
+     * @param prefixes The array of prefixes to check for duplicates.
+     * @throws ParseException If duplicate prefixes are found.
+     */
+    private void checkForDuplicatePrefixes(String[] prefixes) throws ParseException {
+        Set<String> prefixSet = new HashSet<>(Arrays.asList(prefixes));
+        if (prefixes.length != prefixSet.size()) {
+            throw new ParseException("Duplicate prefixes are not allowed.");
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java:70]: I still kindaa think this is sort of a magic literal

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 3]
```diff
@@ -34,37 +37,90 @@ public SortCommand parse(String args) throws ParseException {
...
-        if (prefixes.length == 2) {
-            if (!isValidPrefix(prefixes[1])) {
-                throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, SortCommand.MESSAGE_USAGE));
-            }
-        } else {
-            throw new ParseException("Invalid number of prefixes.");
+    }
+
+    /**
+     * Checks if the input string contains multiple consecutive spaces.
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java:87]: A valid input string can contain multiple consecutive spaces

I think an input consisting of only spaces?

**Review by Wrongian — COMMENTED** [review]
Pretty good

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java (hunk 3 above)
Comment (Wrongian) [reply src/main/java/seedu/address/logic/parser/SortCommandParser.java]: Oke

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java (hunk 1 above)
Comment (carineang) [reply src/main/java/seedu/address/logic/parser/SortCommandParser.java:57]: Nah, I am not going to change it :(

Comment (Wrongian) [reply src/main/java/seedu/address/logic/parser/SortCommandParser.java:57]: oke
