### PR TITLE
Fix: Undo interaction with find

### LINKED ISSUE #106: Bug: Cannot undo find command
When loading the address book contacts for the first time, perform:
1. `find alex`
2. undo

Expected: find filtering is undone

Actual: model does not undo the find filter

### LINKED ISSUE #157: Bug: Unable to undo list command
1. `list` 
2. `find alex`
3. `list`
4. `undo`

Expected: showed alex contact 
Actual: showed the list of all contacts

When I tried to `undo` the `list`, it could not undo `list`. In the command output, it shows `Successfully undone last command`. So I'm unsure if `ListCommand` is an acceptable command to undo?

### PR DESCRIPTION
**Pull request by Wrongian**
Fixes #106 
Fixes #157 

- Rewrite undo/redo logic to use save the model state instead of the address book state

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java [hunk 1]
```diff
@@ -60,8 +60,8 @@ public void execute_filteredList_success() {
                 personToView.getNote().toString());
 
         Model expectedModel = new ModelManager(new AddressBook(model.getAddressBook()), new UserPrefs());
-        expectedModel.commitAddressBook();
```
Comment (clx3210) [inline src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java:63]: Was this previously a bug with the test case?

File: src/main/java/seedu/address/model/ModelState.java [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+import static seedu.address.commons.util.CollectionUtil.requireAllNonNull;
+
+import java.util.Objects;
+import java.util.function.Predicate;
+
+import seedu.address.model.person.Person;
+
+
+/**
+ * State of the model that contains the state of the
```
Comment (clx3210) [inline src/main/java/seedu/address/model/ModelState.java:12]: There seems to be a Javadoc naming issue here

**Review by clx3210 — APPROVED** [review]
Lgtm, but need to update the model class diagram and other command sequence diagrams later on since they would still reference "commitAddressBook"

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 3]
```diff
@@ -72,10 +72,10 @@ public void execute_validIndexFilteredList_success() {
                 Messages.format(personToDelete));
 
         Model expectedModel = new ModelManager(getTypicalAddressBook(), new UserPrefs());
+        showPersonAtIndex(expectedModel, INDEX_FIRST_PERSON);
         expectedModel.deletePerson(personToDelete);
-        showNoPerson(expectedModel);
```
[the remark this answers is not in the document]
Comment (Wrongian) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java:76]: Because the expected and actual mode both use different predicates
This would have test case always return an error

So I just made both test cases use the same predicate

[the remark this answers is not in the document]
Comment (Wrongian) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java:76]: Dunno if there is a better fix

File: src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java (hunk 1 above)
Comment (Wrongian) [reply src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java:63]: Not sure what this means

File: src/main/java/seedu/address/model/ModelState.java (hunk 2 above)
Comment (Wrongian) [reply src/main/java/seedu/address/model/ModelState.java:12]: What is the javadocs naming issue?
Is it the action word thing?

**Comment by Wrongian** [comment]
Oke
Fair enuf

File: src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java (hunk 1 above)
Comment (Wrongian) [reply src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java:63]: The idea why I changed this is because the commit happened before the predicate changed which unintended behaviour since a command is supposed to commit after all the changes happened
this also caused a bug in the test case

So I made it so the commit happens after the predicate changed
which is the intended behaviour

Comment (Wrongian) [reply src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java:63]: I'll resolve it and merge for now
Lmk if this change is not good and I'll try to follow up
