### PR TITLE
Fix unclear assertions

### LINKED ISSUE #233: Bug: Unclear assertions in PinCommandTest and UnpinCommandTest

### PR DESCRIPTION
**Pull request by pranavyey**
Fixes #233

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/PinCommandTest.java [hunk 1]
```diff
@@ -33,8 +33,8 @@ public void execute_validIndex_pinsPerson() throws Exception {
         // Ensure person is now at the top of the list and pinned
         Person pinnedPerson = model.getFilteredPersonList().get(0);
         assertTrue(pinnedPerson.getPin().isPinned());
-        assertEquals(String.format(PinCommand.MESSAGE_PIN_PERSON_SUCCESS, INDEX_FIRST_PERSON.getOneBased()),
-                result.getFeedbackToUser());
+        String ExpectedMessage = String.format(PinCommand.MESSAGE_PIN_PERSON_SUCCESS, INDEX_FIRST_PERSON.getOneBased());
```
Comment (clx3210) [inline src/test/java/seedu/address/logic/commands/PinCommandTest.java:36]: Shall we use lowerCamel case here for variable naming?

File: src/test/java/seedu/address/logic/commands/UnpinCommandTest.java [hunk 2]
```diff
@@ -98,8 +98,9 @@ public void execute_validIndexUnpinnedPerson_returnsMessage() throws Exception {
 
         Person unpinnedPerson = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
         assertFalse(unpinnedPerson.getPin().isPinned());
-        assertEquals(String.format(UnpinCommand.MESSAGE_UNPIN_PERSON_NOT_PINNED, INDEX_FIRST_PERSON.getOneBased()),
-                result.getFeedbackToUser());
+        String ExpectedMessage = String.format(UnpinCommand.MESSAGE_UNPIN_PERSON_NOT_PINNED,
```
Comment (clx3210) [inline src/test/java/seedu/address/logic/commands/UnpinCommandTest.java:101]: same for this

**Review by clx3210 — APPROVED** [review]
lgtm, added some coding convention comments

File: src/test/java/seedu/address/logic/commands/PinCommandTest.java (hunk 1 above)
Comment (pranavyey) [reply src/test/java/seedu/address/logic/commands/PinCommandTest.java]: yep, changed!

File: src/test/java/seedu/address/logic/commands/UnpinCommandTest.java (hunk 2 above)
Comment (pranavyey) [reply src/test/java/seedu/address/logic/commands/UnpinCommandTest.java]: yep, changed!
