### PR TITLE
Fix UI issues

### LINKED ISSUE #256: [PE-D][Tester C] If entires are too long, the Contact Information does not display the entire thing
Not the entire entry can be seen

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: cerulyean/ped#1

### LINKED ISSUE #262: [PE-D][Tester C] Pin icon appears incorrect
I was using linux, and tried pin feature. Pin image appears to be wrong.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: cerulyean/ped#4

### LINKED ISSUE #267: [PE-D][Tester A] Details of person cannot be displayed immediately after editing
**Description**

Displayed details of a person disappears and cannot be clicked after modifying the person.

Reasoning: This may confuse users for a while, as they may keep clicking on the person they edited before clicking someone else.

<br>

**Steps to reproduce** 

1.  Create a person
2. Click on the person in the list
3. Edit the same person in with the Edit command
4. Click repeatedly on the edited person

<br>

**Expected**

The details of the person displays on the right box, with the updated details.

<br>

**Actual** 

The details cannot be displayed.

<br>

**Screenshots**

<br>

**Reasoning for severity**
While this can happen in any scenario, there is a simple fix of this by clicking someone else then clicking the edited person. However, trying to figure this out in the first time may take some time, and doing it repeatedly may be frustrating for the user.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Billy026/ped#3

### LINKED ISSUE #294: [PE-D][Tester E] UI - Clipped Contact Information box
The Client Information box is clipped when the application window is shrunk.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: wzhua02/ped#13

### PR DESCRIPTION
**Pull request by carineang**
Closes #256 
Closes #262
Closes #267 
Closes #294

### CODE REVIEW

**Review by Wrongian — APPROVED** [review]
LGTM

**Comment by Wrongian** [comment]
Seems like very few lines as well

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -210,6 +210,7 @@ private CommandResult executeCommand(String commandText) throws CommandException
             if (commandResult.isExit()) {
                 handleExit();
             }
+            personListPanel.clearSelection();
```
Comment (carineang) [inline src/main/java/seedu/address/ui/MainWindow.java:213]: unfocus a person when each command is called

Comment (Wrongian) [reply src/main/java/seedu/address/ui/MainWindow.java:213]: It was that easy huh...

**Review by Wrongian — APPROVED** [review]
Noice

**Comment by carineang** [comment]
okay i merge now, hopefully there isn't any issues with it
