### PR TITLE
Fix Bugs in Help command

### LINKED ISSUE #135: Bug: Help usage is not updated
Commands such as delete dont have the same usage message as the normal version

Image

Actual:

Image

Suggested fix?:

Image
COMMAND_HELP.put(<command class>.COMMAND_WORD, <command class>.MESSAGE_USAGE)
so dont have to change the help command every time

### PR DESCRIPTION
**Pull request by xinniyee**
Closes #135 #105

### CODE REVIEW

**Comment by Wrongian** [comment]
is using 
DeleteCommand.MESSAGE_USAGE fine?
or is it not good?

every command should have a MESSAGE_USAGE

**Comment by Wrongian** [comment]
image
Whoops I forgot to send an image
like this

so if someone changes the MESSAGE_USAGE of a command dont have to change it in help

File: src/test/java/seedu/address/logic/commands/HelpCommandTest.java [hunk 1]
```diff
@@ -21,14 +21,16 @@ public void execute_helpNoCommand_success() {
...
-                + "Use double quotation marks (\") around each input\n"
-                + "Example: find n/\"Alice\" \"Bob\" p/\"98765432\" a/\"Bedok Central\" t/\"close friend\"";
+        String expectedFeedback = "find"
+                + ": Finds all persons whose specified fields contain any of "
+                + "the given keywords (case-insensitive) and displays them as a list with index numbers.\n"
+                + "Parameters: [n/\"NAME\"] [p/\"PHONE\"] [e/\"EMAIL\"]"
+                + " [a/\"ADDRESS\"] [t/\"TAG\"] \"KEYWORD\" [\"MORE_KEYWORDS\"]...\n"
+                + "Use double quotation marks (\") around multi-word inputs or "
+                + "single keywords to ensure correct parsing.\n"
+                + "Example: " + "find" + " n/\"Alice\" \"Bob\" p/\"98765432\" a/\"Bedok Central\" t/\"close friend\"";
```
Comment (Wrongian) [inline src/test/java/seedu/address/logic/commands/HelpCommandTest.java:33]: Might want to do the same thing here
FindCommand.COMMAND_WORD + FindCommand.MESSAGE_USAGE

Comment (Wrongian) [reply src/test/java/seedu/address/logic/commands/HelpCommandTest.java:33]: i think it should be fine if its left though??
but need to change if find command is changed

Comment (xinniyee) [reply src/test/java/seedu/address/logic/commands/HelpCommandTest.java:33]: This is a test case though, if i compare FindCommand.MESSAGE_USAGE against FindCommand.MESSAGE_USAGE then its a bit useless

**Review by Wrongian — APPROVED** [review]
LGTM :3

File: src/test/java/seedu/address/logic/commands/HelpCommandTest.java (hunk 1 above)
Comment (Wrongian) [reply src/test/java/seedu/address/logic/commands/HelpCommandTest.java:33]: hmmmm
I think should be fine
I approved
I think theres a good argument to be made about it being a test case
