### PR TITLE
Fix: Delete duplicate index

### LINKED ISSUE #161: Bug: Delete with duplicate index
When i `delete i/1 2 2 3`, it deletes person 1-4. We probably need checks to prevent multiple same indexes.

### PR DESCRIPTION
**Pull request by clx3210**
Fixes #161

### CODE REVIEW

File: src/test/java/seedu/address/commons/core/index/IndexIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+import java.util.Set;
+
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
+
+/**
+ * Contains integration tests for Index class with other data structures.
+ */
+public class IndexIntegrationTest {
+    private Set<Index> expectedSetIndexes;
```
Comment (Wrongian) [inline src/test/java/seedu/address/commons/core/index/IndexIntegrationTest.java:15]: Good tests

File: src/main/java/seedu/address/commons/core/index/Index.java [hunk 2]
```diff
@@ -47,6 +47,16 @@ public static Index fromOneBased(int oneBasedIndex) {
         return new Index(oneBasedIndex - 1);
     }
 
+    /**
+     * Returns a hash that is consistent with the index equality definition.
```
Comment (Wrongian) [inline src/main/java/seedu/address/commons/core/index/Index.java:51]: Might want to make this message clearer?

**Review by Wrongian — APPROVED** [review]
Good coverage of tests

File: src/test/java/seedu/address/commons/core/index/IndexTest.java [hunk 3]
```diff
@@ -58,6 +59,23 @@ public void equals() {
         assertFalse(fifthPersonIndex.equals(Index.fromOneBased(1)));
     }
 
+    @Test
+    public void hashCode_sameZeroBased_equal() {
```
Comment (pranavyey) [inline src/test/java/seedu/address/commons/core/index/IndexTest.java:63]: good positive test

File: src/test/java/seedu/address/commons/core/index/IndexTest.java [hunk 4]
```diff
@@ -58,6 +59,23 @@ public void equals() {
...
+        final Index fifthPersonIndex = Index.fromOneBased(5);
+        // same zero-based values -> returns true
+        assertEquals(fifthPersonIndex.hashCode(), Index.fromZeroBased(4).hashCode());
+        assertEquals(fifthPersonIndex.hashCode(), Index.fromOneBased(5).hashCode());
+    }
+
+    @Test
+    public void hashCode_differentZeroBased_notEqual() {
```
Comment (pranavyey) [inline src/test/java/seedu/address/commons/core/index/IndexTest.java:71]: good negative test

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 5]
```diff
@@ -125,6 +126,46 @@ public void execute_invalidIndexesFilteredList_throwsCommandException() {
...
+            expectedModel.deletePerson(person);
+        }
+        expectedModel.commitAddressBook();
+
+        return expectedModel;
+    }
+
+    @Test
+    public void execute_duplicateIndexesFilteredList_duplicatesIgnored() {
+        // hardcoded size based on getTypicalPersons()
```
Comment (pranavyey) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java:142]: posible to make this test more robust?(i.e. without hardcoding)

File: src/test/java/seedu/address/logic/parser/MassOpsIndexParserTest.java [hunk 6]
```diff
@@ -88,5 +90,22 @@ public void parseIndexes_invalidRangeBoundOrder_exceptionThrown() {
         assertEquals(MassOpsIndexParser.MESSAGE_INVALID_RANGE_ORDER, pe.getMessage());
     }
 
+    @Test
+    public void parseIndexes_duplicateIndexes_duplicatesIgnored() {
```
Comment (pranavyey) [inline src/test/java/seedu/address/logic/parser/MassOpsIndexParserTest.java:94]: good test

**Review by pranavyey — APPROVED** [review]
LGTM

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 5 above)
Comment (clx3210) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Updated to specify this as a test precondition instead

File: src/main/java/seedu/address/commons/core/index/Index.java (hunk 2 above)
Comment (clx3210) [reply src/main/java/seedu/address/commons/core/index/Index.java]: Updated to include definitions

File: src/main/java/seedu/address/commons/core/index/Index.java [hunk 7]
```diff
@@ -48,7 +48,8 @@ public static Index fromOneBased(int oneBasedIndex) {
     }
 
     /**
-     * Returns a hash that is consistent with the index equality definition.
+     * Returns a hash code that is consistent with the index equality definition.
+     * If two {@code Index} objects are equal, they must have the same hash code.
```
Comment (Wrongian) [inline src/main/java/seedu/address/commons/core/index/Index.java:52]: 👍
