### PR TITLE
Fix: Error message for pinning/unpinning contact that is already pinned/not pinned

### LINKED ISSUE #137: Bug: No error message pops up for the user when unpinning a contact that is not pinned
I do a pin on index 3, then I do an unpin on index 3
since there is only 1 pin at index one, this is out of index, but no error message is displayed on what the user is supposed to do

### PR DESCRIPTION
**Pull request by pranavyey**
Fixes #137 , #177

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/UnpinCommandTest.java [hunk 1]
```diff
@@ -89,6 +89,19 @@ public void execute_invalidIndex_throwsCommandException() {
...
+    @Test
+    public void execute_validIndexUnpinnedPerson_returnsMessage() throws Exception {
+        Person originalPerson = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
+        assertFalse(originalPerson.getPin().isPinned());
+        UnpinCommand unpinCommand = new UnpinCommand(INDEX_FIRST_PERSON);
+        CommandResult result = unpinCommand.execute(model);
+
+        Person unpinnedPerson = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
+        assertFalse(unpinnedPerson.getPin().isPinned());
+        assertEquals(String.format(UnpinCommand.MESSAGE_UNPIN_PERSON_NOT_PINNED, INDEX_FIRST_PERSON.getOneBased()),
```
Comment (clx3210) [inline src/test/java/seedu/address/logic/commands/UnpinCommandTest.java:101]: Minor nitpick: the expected message could be abstracted into an `expectedMessage` variable

File: src/test/java/seedu/address/logic/commands/PinCommandTest.java [hunk 2]
```diff
@@ -47,6 +46,16 @@ public void execute_invalidIndex_throwsCommandException() {
                 Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
     }
 
+    @Test
+    public void execute_validIndexAlreadyPinnedPerson_returnsMessage() throws Exception {
+        PinCommand pinCommand = new PinCommand(INDEX_FIRST_PERSON);
+        pinCommand.execute(model);
+        PinCommand newPinCommand = new PinCommand(INDEX_FIRST_PERSON);
+        CommandResult newResult = newPinCommand.execute(model);
+        assertEquals(String.format(PinCommand.MESSAGE_PIN_PERSON_ALREADY_PINNED, INDEX_FIRST_PERSON.getOneBased()),
```
Comment (clx3210) [inline src/test/java/seedu/address/logic/commands/PinCommandTest.java:55]: Same as the comment below

**Review by clx3210 — APPROVED** [review]
LGTM
