### PR TITLE
Fix: Sort command bug

### LINKED ISSUE #134: Bug: Adding a new client contact after sorting the list does not place the new client contact in sorted order
how to recreate bug:
1. sort 
2. add a new person
I will add it to the bottom instead of in sorted order

### LINKED ISSUE #136: Bug: Doing a find then a sort shows the full sorted unfiltered list
Might be 100% intended? should it be in the final product? might need discussion

### LINKED ISSUE #184: Enhancement: Allow sorting combinations

### PR DESCRIPTION
**Pull request by carineang**
Fixes #136 
Closes #184

### CODE REVIEW

File: src/main/java/seedu/address/model/person/UniquePersonList.java [hunk 1]
```diff
@@ -201,27 +201,54 @@ private boolean personsAreUnique(List<Person> persons) {
...
-        case "a/":
-            sortByAddress();
-            break;
-        case "t/":
-            sortByTags();
-            break;
-        default:
-            break;
+    public void sortBy(String... prefixes) {
+        if (prefixes.length == 1) {
```
Comment (clx3210) [inline src/main/java/seedu/address/model/person/UniquePersonList.java:207]: Method length here might be way too long, can consider abstracting into private methods?

File: docs/UserGuide.md [hunk 2]
```diff
@@ -248,15 +248,19 @@ Examples:
...
 
 * `sort n/` sorts contacts by ascending names.
 * `sort p/` sorts contacts by ascending phone numbers.
 * `sort e/` sorts contacts by ascending emails.
 * `sort a/` sorts contacts by ascending addresses.
 * `sort t/` sorts contacts by ascending tags.
+* `sort t/ n/` sorts contacts by tags first, within the tags, sort by names.
+* `sort t/ p/` sorts contacts by tags first, within the tags, sort by phone numbers.
+* `sort t/ e/` sorts contacts by tags first, within the tags, sort by emails.
+* `sort t/ a/` sorts contacts by tags first, within the tags, sort by addresses.
```
Comment (Wrongian) [inline docs/UserGuide.md:263]: May want to clarify what this means in simpler language
I dont think the language is that clear especially for someone that may not be tech savvy
May also want to specify whether the contacts are sorted in ascending or descending order for this section as well

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 3]
```diff
@@ -7,7 +7,7 @@
 import static seedu.address.logic.parser.CliSyntax.PREFIX_NAME;
 import static seedu.address.logic.parser.CliSyntax.PREFIX_PHONE;
 import static seedu.address.logic.parser.CliSyntax.PREFIX_TAG;
-import static seedu.address.model.Model.PREDICATE_SHOW_ALL_PERSONS;
+//import static seedu.address.model.Model.PREDICATE_SHOW_ALL_PERSONS;
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:10]: I think this comment should be removed?
should not have comments like this in the final ver?

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 4]
```diff
@@ -21,24 +21,26 @@ public class SortCommand extends Command {
     public static final String COMMAND_WORD = "sort";
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Sort all persons by the attribute specified "
             + "and displays them as a list with index numbers.\n"
-            + "Parameters: "
+            + "Acceptable prefixes: "
             + "[" + PREFIX_NAME + "] "
             + "[" + PREFIX_PHONE + "] "
             + "[" + PREFIX_EMAIL + "] "
             + "[" + PREFIX_ADDRESS + "] "
             + "[" + PREFIX_TAG + "] \n"
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:29]: Good use of abstraction

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 5]
```diff
@@ -21,24 +21,26 @@ public class SortCommand extends Command {
...
      *
-     * @param prefix The prefix indicating the attribute to sort by.
+     * @param prefixes The prefixes indicating the attribute to sort by.
      */
-    public SortCommand(String prefix) {
-        this.prefix = prefix;
-        requireNonNull(prefix);
+    public SortCommand(String... prefixes) {
+        if (prefixes == null || prefixes.length == 0) {
+            throw new IllegalArgumentException("Prefixes cannot be null or empty");
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:41]: I think this could be considered a magic literal, may want to make it a constnat

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 6]
```diff
@@ -21,24 +21,26 @@ public class SortCommand extends Command {
...
      * Constructs a SortCommand to sort the address book based on specified prefix.
      *
-     * @param prefix The prefix indicating the attribute to sort by.
+     * @param prefixes The prefixes indicating the attribute to sort by.
      */
-    public SortCommand(String prefix) {
-        this.prefix = prefix;
-        requireNonNull(prefix);
+    public SortCommand(String... prefixes) {
+        if (prefixes == null || prefixes.length == 0) {
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:40]: I assume that if IllegalArgumentException is thrown it is probably the user's fault
If I am reading the code correctly, 
I dont think if prefixes is null, its the user's fault?

Comment (Wrongian) [reply src/main/java/seedu/address/logic/commands/SortCommand.java:40]: Perhaps make it an assertion instead if its the coder's fault if this happens?

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 7]
```diff
@@ -51,16 +53,21 @@ public SortCommand(String prefix) {
...
     public CommandResult execute(Model model) {
         requireNonNull(model);
-        model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
-        model.updateSortedFilteredPersonList(prefix);
+        model.updateSortedPersonList(prefixes);
+        model.updateSortedFilteredPersonList(prefixes);
         model.commitAddressBook();
 
-        logger.info("SortCommand execution completed. List sorted by: " + prefix);
+        logger.info("SortCommand execution completed. List sorted by: " + prefixes);
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:60]: Good use of logging at the end of the execution of the command

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 8]
```diff
@@ -51,16 +53,21 @@ public SortCommand(String prefix) {
...
 
-    public String getSortPrefix() {
-        return prefix;
+    /**
+     * Returns the prefixes that are used to sort the address book.
+     *
+     * @return The array of prefixes specifying the attributes which the address book is sorted.
+     */
+    public String[] getSortPrefix() {
+        return prefixes;
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:71]: Good getter

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 9]
```diff
@@ -27,30 +23,48 @@ public class SortCommandParser implements Parser<SortCommand> {
...
+            throw new ParseException("Invalid number of prefixes.");
+        }
+        for (String prefix : prefixes) {
+            if (!isValidPrefix(prefix)) {
+                throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, SortCommand.MESSAGE_USAGE));
+            }
+        }
+        if (args.contains("  ")) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, SortCommand.MESSAGE_USAGE));
+        }
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java:54]: This looks like a very long method
May want to shorten it

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 10]
```diff
@@ -27,30 +23,48 @@ public class SortCommandParser implements Parser<SortCommand> {
...
 
-        default:
-            logger.warning("Invalid sorting prefix provided: " + trimmedArgs);
-            throw new ParseException("Invalid prefix used.");
-        }
+    /**
+     * Validates if a given prefix is a recognized sorting prefix.
+     *
+     * @param prefix The prefix string to validate.
+     * @return True if the prefix is valid, false otherwise.
```
Comment (Wrongian) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java:64]: Very clear documentation of the method

File: src/main/java/seedu/address/model/AddressBook.java [hunk 11]
```diff
@@ -149,6 +154,11 @@ public boolean equals(Object other) {
         return persons.equals(otherAddressBook.persons);
     }
 
+    /**
+     * Returns the hash code of this AddressBook.
+     *
+     * @return The hash code of this address book.
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/AddressBook.java:160]: The description uses "Addressbook" but the return description uses "address book"
May want to make this consistent

File: src/main/java/seedu/address/model/ModelManager.java [hunk 12]
```diff
@@ -159,18 +192,33 @@ public ObservableList<String> getCommandInputHistoryList() {
...
         requireNonNull(prefix);
         addressBook.updateSortedList(prefix);
     }
 
+    /**
+     * Updates the sorted person list based on the given prefix. The prefix is used to
+     * filter the list of persons in the address book and sort the resulting filtered list.
+     *
+     * @param prefix The string prefix used to filter and sort the person list.
+     * @throws NullPointerException if prefix is null.
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/ModelManager.java:212]: Should be the gold standard of javadocs descriptions

File: src/main/java/seedu/address/model/person/FilteredPersonList.java [hunk 13]
```diff
@@ -0,0 +1,159 @@
...
+     * Get the sorted list.
+     *
+     * @return the sorted list.
+     */
+    public SortedList<Person> getSortedList() {
+        return sortedList;
+    }
+
+    /**
+     * Sorts the list of persons based on the specified prefix such as name, phone number, email address, address, tags.
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/FilteredPersonList.java:40]: name acktuallyy not a prefix
May want to write
lets say n/ for name
p/ for phone number
etc

File: src/main/java/seedu/address/model/person/FilteredPersonList.java [hunk 14]
```diff
@@ -0,0 +1,159 @@
...
+                sortByPhoneNumber();
+                break;
+            case "e/":
+                sortByEmailAddress();
+                break;
+            case "a/":
+                sortByAddress();
+                break;
+            default:
+                throw new IllegalArgumentException("Invalid sort prefix: " + prefixes[0]);
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/FilteredPersonList.java:63]: May be considered a magic literal, may want to make this a constant belonging to the class

File: src/main/java/seedu/address/model/person/FilteredPersonList.java [hunk 15]
```diff
@@ -0,0 +1,159 @@
...
+                sortByName();
+                break;
+            case "p/":
+                sortByPhoneNumber();
+                break;
+            case "e/":
+                sortByEmailAddress();
+                break;
+            case "a/":
+                sortByAddress();
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/FilteredPersonList.java:60]: May want to use
instead of n/ 
use PREFIX_NAME
instead for better abstraction

File: src/main/java/seedu/address/model/person/FilteredPersonList.java [hunk 16]
```diff
@@ -0,0 +1,159 @@
...
+                    sortByNameWithinTagsFiltered();
+                    break;
+                case "p/":
+                    sortByPhoneNumberWithinTagsFiltered();
+                    break;
+                case "e/":
+                    sortByEmailAddressWithinTagsFiltered();
+                    break;
+                case "a/":
+                    sortByAddressWithinTagsFiltered();
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/FilteredPersonList.java:78]: same comment about abstraction here

File: src/main/java/seedu/address/model/person/FilteredPersonList.java [hunk 17]
```diff
@@ -0,0 +1,159 @@
...
+                default:
+                    throw new IllegalArgumentException("Invalid combination of prefixes: "
+                            + String.join(", ", prefixes));
+                }
+            } else {
+                throw new IllegalArgumentException("Invalid sort prefix combination: "
+                        + String.join(", ", prefixes));
+            }
+        } else {
+            throw new IllegalArgumentException("Invalid number of prefixes or combination of prefixes.");
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/FilteredPersonList.java:89]: All of these may be considered magic literals

File: src/main/java/seedu/address/model/person/FilteredPersonList.java [hunk 18]
```diff
@@ -0,0 +1,159 @@
...
+    }
+
+    /**
+     * Sort the list first by tags, then by address within each tag group.
+     */
+    private void sortByAddressWithinTagsFiltered() {
+        sortedList.setComparator(Comparator.comparing((Person p) -> p.getTags().toString())
+                .thenComparing(p -> p.getAddress().toString()));
+    }
+}
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/FilteredPersonList.java:159]: Very clean and good use of functional programming
Though I think it could be better formatted for readability
But I would say this is optional?

File: src/main/java/seedu/address/model/person/UniquePersonList.java [hunk 19]
```diff
@@ -201,27 +201,54 @@ private boolean personsAreUnique(List<Person> persons) {
...
+                sortByName();
+                break;
+            case "p/":
+                sortByPhoneNumber();
+                break;
+            case "e/":
+                sortByEmailAddress();
+                break;
+            case "a/":
+                sortByAddress();
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/UniquePersonList.java:222]: Same issue with abstraction here

File: src/main/java/seedu/address/model/person/UniquePersonList.java [hunk 20]
```diff
@@ -201,27 +201,54 @@ private boolean personsAreUnique(List<Person> persons) {
...
+                break;
+            default:
+                throw new IllegalArgumentException("Invalid sort prefix: " + prefixes[0]);
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/UniquePersonList.java:225]: This could be considered a magic literal

File: src/main/java/seedu/address/model/person/UniquePersonList.java [hunk 21]
```diff
@@ -201,27 +201,54 @@ private boolean personsAreUnique(List<Person> persons) {
...
+                case "n/":
+                    sortByNameWithinTags();
+                    break;
+                case "p/":
+                    sortByPhoneNumberWithinTags();
+                    break;
+                case "e/":
+                    sortByEmailAddressWithinTags();
+                    break;
+                case "a/":
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/UniquePersonList.java:239]: same comment about abstraction here

File: src/main/java/seedu/address/model/person/UniquePersonList.java [hunk 22]
```diff
@@ -201,27 +201,54 @@ private boolean personsAreUnique(List<Person> persons) {
...
+                default:
+                    throw new IllegalArgumentException("Invalid combination of prefixes: "
+                            + String.join(", ", prefixes));
+                }
+            } else {
+                throw new IllegalArgumentException("Invalid sort prefix combination: "
+                        + String.join(", ", prefixes));
+            }
+        } else {
+            throw new IllegalArgumentException("Invalid number of prefixes or combination of prefixes.");
```
Comment (Wrongian) [inline src/main/java/seedu/address/model/person/UniquePersonList.java:251]: same comment about magic literals here

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 23]
```diff
@@ -177,7 +177,12 @@ public ObservableList<String> getCommandInputHistoryList() {
...
 
         @Override
-        public void updateSortedFilteredPersonList(String prefix) {
+        public void updateSortedPersonList(String... prefix) {
+            throw new AssertionError("This method should not be called.");
+        }
+
+        @Override
+        public void updateSortedFilteredPersonList(String... prefix) {
             throw new AssertionError("This method should not be called.");
```
Comment (Wrongian) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java:186]: This could be considered a magic literal

File: src/test/java/seedu/address/logic/commands/SortCommandTest.java [hunk 24]
```diff
@@ -126,4 +127,22 @@ public void execute_sortByTags_success() throws DuplicatePersonException {
...
+    }
+
+    @Test
+    public void constructor_emptyPrefixes_throwsIllegalArgumentException() {
+        String[] prefixes = new String[0];
+        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
+            new SortCommand(prefixes);
+        });
+        assertEquals("Prefixes cannot be null or empty", exception.getMessage());
+    }
```
Comment (Wrongian) [inline src/test/java/seedu/address/logic/commands/SortCommandTest.java:147]: Good coverage of tests

File: src/test/java/seedu/address/logic/parser/SortCommandParserTest.java [hunk 25]
```diff
@@ -20,46 +24,88 @@ public void setUp() {
...
+        assertEquals("Invalid number of prefixes.", exception.getMessage());
+    }
+
+    @Test
+    public void parse_extraSpacesBetweenPrefixes_throwsParseException() {
+        String input = "t/  n/";
+        ParseException exception = assertThrows(ParseException.class, () -> {
+            parser.parse(input);
+        });
+        assertEquals(String.format(MESSAGE_INVALID_COMMAND_FORMAT, SortCommand.MESSAGE_USAGE), exception.getMessage());
```
Comment (Wrongian) [inline src/test/java/seedu/address/logic/parser/SortCommandParserTest.java:109]: Good coverage of tests

File: src/test/java/seedu/address/model/ModelManagerTest.java [hunk 26]
```diff
@@ -318,17 +318,43 @@ public void getFilteredPersonList_modifyList_throwsUnsupportedOperationException
...
+    public void updateSortedFilteredPersonList_emptyList_noEffect() {
+        AddressBook emptyAddressBook = new AddressBook();
+        modelManager = new ModelManager(emptyAddressBook, new UserPrefs());
+        modelManager.updateSortedFilteredPersonList("n/");
+        ObservableList<Person> filteredList = modelManager.getFilteredPersonList();
+        assertTrue(filteredList.isEmpty());
+    }
+
+    @Test
+    public void updateSortedFilteredPersonList_multiplePersonsWithSamePrefix_sortedWithSortByFilteredList() {
```
Comment (Wrongian) [inline src/test/java/seedu/address/model/ModelManagerTest.java:347]: This is the longest method I have ever seen in my life
I dont know if this is allowed for tests
I hope it does it would be so peak

**Review by Wrongian — APPROVED** [review]
Test cases is very extensive
Documentation of methods are excellent

Just a few comments on magic literals and abstraction 
as well as some minor things that I saw

**Review by Wrongian — COMMENTED** [review]
Whoops I meant to comment to approve

Lemme know your opinions of the comments
if you are fine with them can just merge

File: src/main/java/seedu/address/model/person/UniquePersonList.java (hunk 1 above)
Comment (carineang) [reply src/main/java/seedu/address/model/person/UniquePersonList.java:207]: Fixed

File: src/main/java/seedu/address/logic/commands/SortCommand.java (hunk 3 above)
Comment (carineang) [reply src/main/java/seedu/address/logic/commands/SortCommand.java:10]: Fixed

**Comment by carineang** [comment]
Mostly fixed, ready to merge.
