### PR TITLE
Fix email usage message

### LINKED ISSUE #257: [PE-D][Tester C] "Valid" email address not accepted
According to the requirements, aas..d@as.com is a valid email address. Yet it cannot be accepted.

The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: cerulyean/ped#2

### PR DESCRIPTION
**Pull request by Wrongian**
Fixes #257

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Email.java [hunk 1]
```diff
@@ -15,6 +15,7 @@ public class Email {
             + "1. The local-part should only contain alphanumeric characters and these special characters, excluding "
             + "the parentheses, (" + SPECIAL_CHARACTERS + "). The local-part may not start or end with any special "
             + "characters.\n"
+            + "A special character must be followed by at least one alphanumeric character.\n"
```
Comment (clx3210) [inline src/main/java/seedu/address/model/person/Email.java:18]: Nice

**Review by clx3210 — APPROVED** [review]
LGTM
